
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trim
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trim-service

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - trim-service

  trim-api:
    build:
      context: ./  # Root context for the build
      dockerfile: ./Trim-Api/Dockerfile
    container_name: trim-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - trim-service

volumes:
  mysql_data:

networks:
  trim-service: