package trim.domains.avatar.dao.entity.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import trim.common.interfaces.KeyedEnum;

@Getter
@RequiredArgsConstructor
public enum ClothForURL implements KeyedEnum {
    RED_R1("red_r1"),
    RED_R2("red_r2"),
    RED_R3("red_r3"),
    RED_R4("red_r4"),
    RED_R5("red_r5"),
    RED_R6("red_r6"),
    RED_R7("red_r7"),
    RED_R8("red_r8"),
    RED_R9("red_r9"),
    RED_R10("red_r10"),
    RED_R11("red_r11"),
    RED_R12("red_r12"),

    PINK_R1("pink_r1"),
    PINK_R2("pink_r2"),
    PINK_R3("pink_r3"),
    PINK_R4("pink_r4"),
    PINK_R5("pink_r5"),
    PINK_R6("pink_r6"),
    PINK_R7("pink_r7"),
    PINK_R8("pink_r8"),
    PINK_R9("pink_r9"),
    PINK_R10("pink_r10"),
    PINK_R11("pink_r11"),
    PINK_R12("pink_r12"),

    ORANGE_R1("orange_r1"),
    ORANGE_R2("orange_r2"),
    ORANGE_R3("orange_r3"),
    ORANGE_R4("orange_r4"),
    ORANGE_R5("orange_r5"),
    ORANGE_R6("orange_r6"),
    ORANGE_R7("orange_r7"),
    ORANGE_R8("orange_r8"),
    ORANGE_R9("orange_r9"),
    ORANGE_R10("orange_r10"),
    ORANGE_R11("orange_r11"),
    ORANGE_R12("orange_r12"),

    YELLOW_R1("yellow_r1"),
    YELLOW_R2("yellow_r2"),
    YELLOW_R3("yellow_r3"),
    YELLOW_R4("yellow_r4"),
    YELLOW_R5("yellow_r5"),
    YELLOW_R6("yellow_r6"),
    YELLOW_R7("yellow_r7"),
    YELLOW_R8("yellow_r8"),
    YELLOW_R9("yellow_r9"),
    YELLOW_R10("yellow_r10"),
    YELLOW_R11("yellow_r11"),
    YELLOW_R12("yellow_r12"),

    YELLOW_GREEN_R1("yellow_green_r1"),
    YELLOW_GREEN_R2("yellow_green_r2"),
    YELLOW_GREEN_R3("yellow_green_r3"),
    YELLOW_GREEN_R4("yellow_green_r4"),
    YELLOW_GREEN_R5("yellow_green_r5"),
    YELLOW_GREEN_R6("yellow_green_r6"),
    YELLOW_GREEN_R7("yellow_green_r7"),
    YELLOW_GREEN_R8("yellow_green_r8"),
    YELLOW_GREEN_R9("yellow_green_r9"),
    YELLOW_GREEN_R10("yellow_green_r10"),
    YELLOW_GREEN_R11("yellow_green_r11"),
    YELLOW_GREEN_R12("yellow_green_r12"),

    EMERALD_GREEN_R1("emerald_green_r1"),
    EMERALD_GREEN_R2("emerald_green_r2"),
    EMERALD_GREEN_R3("emerald_green_r3"),
    EMERALD_GREEN_R4("emerald_green_r4"),
    EMERALD_GREEN_R5("emerald_green_r5"),
    EMERALD_GREEN_R6("emerald_green_r6"),
    EMERALD_GREEN_R7("emerald_green_r7"),
    EMERALD_GREEN_R8("emerald_green_r8"),
    EMERALD_GREEN_R9("emerald_green_r9"),
    EMERALD_GREEN_R10("emerald_green_r10"),
    EMERALD_GREEN_R11("emerald_green_r11"),
    EMERALD_GREEN_R12("emerald_green_r12"),

    SKY_BLUE_R1("sky_blue_r1"),
    SKY_BLUE_R2("sky_blue_r2"),
    SKY_BLUE_R3("sky_blue_r3"),
    SKY_BLUE_R4("sky_blue_r4"),
    SKY_BLUE_R5("sky_blue_r5"),
    SKY_BLUE_R6("sky_blue_r6"),
    SKY_BLUE_R7("sky_blue_r7"),
    SKY_BLUE_R8("sky_blue_r8"),
    SKY_BLUE_R9("sky_blue_r9"),
    SKY_BLUE_R10("sky_blue_r10"),
    SKY_BLUE_R11("sky_blue_r11"),
    SKY_BLUE_R12("sky_blue_r12"),

    LAVENDER_R1("lavender_r1"),
    LAVENDER_R2("lavender_r2"),
    LAVENDER_R3("lavender_r3"),
    LAVENDER_R4("lavender_r4"),
    LAVENDER_R5("lavender_r5"),
    LAVENDER_R6("lavender_r6"),
    LAVENDER_R7("lavender_r7"),
    LAVENDER_R8("lavender_r8"),
    LAVENDER_R9("lavender_r9"),
    LAVENDER_R10("lavender_r10"),
    LAVENDER_R11("lavender_r11"),
    LAVENDER_R12("lavender_r12"),

    PURPLE_R1("purple_r1"),
    PURPLE_R2("purple_r2"),
    PURPLE_R3("purple_r3"),
    PURPLE_R4("purple_r4"),
    PURPLE_R5("purple_r5"),
    PURPLE_R6("purple_r6"),
    PURPLE_R7("purple_r7"),
    PURPLE_R8("purple_r8"),
    PURPLE_R9("purple_r9"),
    PURPLE_R10("purple_r10"),
    PURPLE_R11("purple_r11"),
    PURPLE_R12("purple_r12"),

    WHITE_R1("white_r1"),
    WHITE_R2("white_r2"),
    WHITE_R3("white_r3"),
    WHITE_R4("white_r4"),
    WHITE_R5("white_r5"),
    WHITE_R6("white_r6"),
    WHITE_R7("white_r7"),
    WHITE_R8("white_r8"),
    WHITE_R9("white_r9"),
    WHITE_R10("white_r10"),
    WHITE_R11("white_r11"),
    WHITE_R12("white_r12"),

    GRAY_R1("gray_r1"),
    GRAY_R2("gray_r2"),
    GRAY_R3("gray_r3"),
    GRAY_R4("gray_r4"),
    GRAY_R5("gray_r5"),
    GRAY_R6("gray_r6"),
    GRAY_R7("gray_r7"),
    GRAY_R8("gray_r8"),
    GRAY_R9("gray_r9"),
    GRAY_R10("gray_r10"),
    GRAY_R11("gray_r11"),
    GRAY_R12("gray_r12"),

    BLACK_R1("black_r1"),
    BLACK_R2("black_r2"),
    BLACK_R3("black_r3"),
    BLACK_R4("black_r4"),
    BLACK_R5("black_r5"),
    BLACK_R6("black_r6"),
    BLACK_R7("black_r7"),
    BLACK_R8("black_r8"),
    BLACK_R9("black_r9"),
    BLACK_R10("black_r10"),
    BLACK_R11("black_r11"),
    BLACK_R12("black_r12");

    private final String key;
}
