package trim.domains.avatar.dao.entity.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import trim.common.interfaces.KeyedEnum;

@Getter
@RequiredArgsConstructor
public enum ClothForURL implements KeyedEnum {
    RED_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_1.svg"),
    RED_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_2.svg"),
    RED_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_3.svg"),
    RED_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_4.svg"),
    RED_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_5.svg"),
    RED_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_7.svg"),
    RED_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_9.svg"),
    RED_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_10.svg"),
    RED_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_11.svg"),
    RED_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesR_12.svg"),

    PINK_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_1.svg"),
    PINK_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_2.svg"),
    PINK_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_3.svg"),
    PINK_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_4.svg"),
    PINK_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_5.svg"),
    PINK_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_7.svg"),
    PINK_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_9.svg"),
    PINK_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_10.svg"),
    PINK_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_11.svg"),
    PINK_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesPink_12.svg"),

    ORANGE_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_1.svg"),
    ORANGE_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_2.svg"),
    ORANGE_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_3.svg"),
    ORANGE_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_4.svg"),
    ORANGE_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_5.svg"),
    ORANGE_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_7.svg"),
    ORANGE_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_9.svg"),
    ORANGE_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_10.svg"),
    ORANGE_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_11.svg"),
    ORANGE_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesO_12.svg"),

    YELLOW_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_1.svg"),
    YELLOW_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_2.svg"),
    YELLOW_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_3.svg"),
    YELLOW_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_4.svg"),
    YELLOW_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_5.svg"),
    YELLOW_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_7.svg"),
    YELLOW_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_9.svg"),
    YELLOW_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_10.svg"),
    YELLOW_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_11.svg"),
    YELLOW_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clothesY_12.svg"),

    YELLOW_GREEN_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_1.svg"),
    YELLOW_GREEN_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_2.svg"),
    YELLOW_GREEN_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_3.svg"),
    YELLOW_GREEN_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_4.svg"),
    YELLOW_GREEN_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_5.svg"),
    YELLOW_GREEN_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_7.svg"),
    YELLOW_GREEN_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_9.svg"),
    YELLOW_GREEN_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_10.svg"),
    YELLOW_GREEN_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_11.svg"),
    YELLOW_GREEN_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesYG_12.svg"),

    EMERALD_GREEN_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_1.svg"),
    EMERALD_GREEN_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_2.svg"),
    EMERALD_GREEN_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_3.svg"),
    EMERALD_GREEN_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_4.svg"),
    EMERALD_GREEN_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_5.svg"),
    EMERALD_GREEN_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_7.svg"),
    EMERALD_GREEN_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_9.svg"),
    EMERALD_GREEN_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_10.svg"),
    EMERALD_GREEN_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_11.svg"),
    EMERALD_GREEN_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesAG_12.svg"),


    SKY_BLUE_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_1.svg"),
    SKY_BLUE_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_2.svg"),
    SKY_BLUE_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_3.svg"),
    SKY_BLUE_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_4.svg"),
    SKY_BLUE_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_5.svg"),
    SKY_BLUE_R6("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_6.svg"),
    SKY_BLUE_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_7.svg"),
    SKY_BLUE_R8("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_8.svg"),
    SKY_BLUE_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_9.svg"),
    SKY_BLUE_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_10.svg"),
    SKY_BLUE_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_11.svg"),
    SKY_BLUE_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesSB_12.svg"),

    LAVENDER_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_1.svg"),
    LAVENDER_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_2.svg"),
    LAVENDER_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_3.svg"),
    LAVENDER_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_4.svg"),
    LAVENDER_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_5.svg"),
    LAVENDER_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_7.svg"),
    LAVENDER_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_9.svg"),
    LAVENDER_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_10.svg"),
    LAVENDER_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_11.svg"),
    LAVENDER_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesL_12.svg"),

    PURPLE_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_1.svg"),
    PURPLE_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_2.svg"),
    PURPLE_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_3.svg"),
    PURPLE_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_4.svg"),
    PURPLE_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_5.svg"),
    PURPLE_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_7.svg"),
    PURPLE_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_9.svg"),
    PURPLE_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_10.svg"),
    PURPLE_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_11.svg"),
    PURPLE_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesP_12.svg"),

    WHITE_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_1.svg"),
    WHITE_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_2.svg"),
    WHITE_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_3.svg"),
    WHITE_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_4.svg"),
    WHITE_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_5.svg"),
    WHITE_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_7.svg"),
    WHITE_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_9.svg"),
    WHITE_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_10.svg"),
    WHITE_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_11.svg"),
    WHITE_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesW_12.svg"),

    GRAY_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_12.svg"),
    GRAY_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_5.svg"),
    GRAY_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_10.svg"),
    GRAY_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_8.svg"),
    GRAY_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_7.svg"),
    GRAY_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_6.svg"),
    GRAY_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_4.svg"),
    GRAY_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_3.svg"),
    GRAY_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_2.svg"),
    GRAY_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatar_clotesR_1.svg"),

    BLACK_R1("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_1.svg"),
    BLACK_R2("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_2.svg"),
    BLACK_R3("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_3.svg"),
    BLACK_R4("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_4.svg"),
    BLACK_R5("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_5.svg"),
    BLACK_R7("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_7.svg"),
    BLACK_R9("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_9.svg"),
    BLACK_R10("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_10.svg"),
    BLACK_R11("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_11.svg"),
    BLACK_R12("https://storage.googleapis.com/trim-cloud-bucket/Avatr_clothesB_12.svg");


    private final String key;
}
