## env file -> resources 패키지 아래에 생성
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trim?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: springproject
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
