server:
  port: 8080

spring:
  profiles:
    include:
      - domain
      - infra

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    path: /swagger-ui.html
  use-fqn: true